name: Deploy Textual App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download nltk Data
      run: |
        python -m nltk.downloader punkt

    - name: Run Textual App and Generate Output
      run: |
        # This assumes that textual-web generates static output to a directory like `./public`
        textual-web --config ganglion.toml

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: public  # This should be the folder where the static output is saved
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
