name: Deploy Textual App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download nltk Data
      run: |
        python -m nltk.downloader punkt

    - name: Run Textual App in Background
      run: |
        nohup textual-web --config ganglion.toml > output.log 2>&1 &
        sleep 5  # Allow time for output to be generated

    - name: List Files in Directory (for Debugging)
      run: ls -al

    - name: Display output.log Content (for Debugging)
      if: always()
      run: cat output.log

    - name: Upload Output Log
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: output-log
        path: output.log
